# Generated by Django 5.0.2 on 2024-02-23 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions',
                                    to='gap.room'),
            preserve_default=False,
        ),
    ]
