# Generated by Django 5.0.2 on 2024-02-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0002_opinion_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='opinion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gap.opinion'),
            preserve_default=False,
        ),
    ]
